[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build && npx prisma generate"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
PORT = "3000"
LOG_LEVEL = "warn"
TIMEZONE = "America/Argentina/Buenos_Aires"
LOCALE = "es-AR"
CURRENCY = "ARS"
JWT_EXPIRES_IN = "7d"
VITE_APP_NAME = "BarberPro"
VITE_APP_VERSION = "1.0.0"
MAX_FILE_SIZE = "5242880"
UPLOAD_DIR = "./uploads"
ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/webp"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX_REQUESTS = "200"
BCRYPT_SALT_ROUNDS = "12"
ENABLE_SWAGGER = "false"
HEALTH_CHECK_TIMEOUT = "5000"
HEALTH_CHECK_INTERVAL = "30000"
FROM_EMAIL = "noreply@barberpro.com.ar"
SMTP_PORT = "587"

[environments.production]
variables = { }

[environments.staging]
variables = { }