name: Test Failure Report
description: Report failing automated or manual tests
title: "[TEST FAILURE] "
labels: ["test-failure", "needs-investigation"]
body:
  - type: markdown
    attributes:
      value: |
        ## Test Failure Report
        Use this template to report failing tests in the BarberPro test suite.

  - type: dropdown
    id: test_type
    attributes:
      label: Test Type
      description: What type of test is failing?
      options:
        - Unit Test (Jest)
        - Integration Test
        - E2E Test (Playwright)
        - Performance Test
        - Security Test
        - Manual Test
        - Regression Test
    validations:
      required: true

  - type: input
    id: test_name
    attributes:
      label: Test Name/File
      description: "Example: user-auth.test.ts, booking-flow.spec.ts"
      placeholder: "test-file-name.test.ts"
    validations:
      required: true

  - type: dropdown
    id: failure_frequency
    attributes:
      label: Failure Frequency
      description: How often does this test fail?
      options:
        - Always fails
        - Intermittent (flaky)
        - Only in CI
        - Only locally
        - Only on specific browsers/devices
    validations:
      required: true

  - type: textarea
    id: error_message
    attributes:
      label: Error Message
      description: Full error message from test failure
      placeholder: "Paste the complete error message here..."
    validations:
      required: true

  - type: textarea
    id: test_logs
    attributes:
      label: Test Logs
      description: Relevant logs from test execution
      placeholder: "Paste relevant log output..."

  - type: input
    id: environment_details
    attributes:
      label: Environment Details
      description: "OS, Node version, browser version if applicable"
      placeholder: "macOS 14, Node 18.17, Chrome 118"

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: How to reproduce this test failure
      placeholder: |
        1. Run command: npm run test:e2e
        2. Navigate to specific test
        3. Observe failure at step X

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Test Behavior
      description: What should the test do when passing?
      placeholder: "Test should pass by..."

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Test Behavior
      description: What is the test actually doing?
      placeholder: "Test is failing because..."

  - type: checkboxes
    id: argentina_context
    attributes:
      label: Argentina-Specific Context
      description: Check if this relates to Argentina market features
      options:
        - label: Payment integration (MercadoPago)
        - label: Localization (Spanish language)
        - label: Timezone handling (Argentina timezone)
        - label: Phone/address format validation
        - label: Network performance simulation
        - label: Mobile testing on Argentina devices

  - type: textarea
    id: investigation_notes
    attributes:
      label: Investigation Notes
      description: Any debugging or investigation already done
      placeholder: "What have you already tried to fix this?"

  - type: checkboxes
    id: checklist
    attributes:
      label: Test Failure Checklist
      options:
        - label: I have run the test multiple times to confirm failure pattern
          required: true
        - label: I have checked if this is a known issue in existing issues
          required: true
        - label: I have included complete error messages and logs
          required: true