# AFIP Compliance Configuration
afip_compliance:
  # Electronic Invoicing
  electronic_invoicing:
    integration_status: "active"
    api_endpoint: "https://servicios1.afip.gov.ar/wsfev1/service.asmx"

    # Certificate Management
    certificates:
      production_cert:
        path: "/etc/ssl/afip/production.crt"
        expiry_date: "2025-12-31"
        auto_renewal: "enabled"

      private_key:
        path: "/etc/ssl/afip/production.key"
        encryption: "RSA-2048"
        secure_storage: "AWS Secrets Manager"

    # Invoice Generation
    invoice_automation:
      real_time_generation: "enabled"
      backup_generation: "enabled"
      error_handling: "automatic_retry"

      # Invoice Templates
      templates:
        - type: "Service Invoice"
          code: "001"
          format: "XML"
          validation: "AFIP_compliant"

        - type: "Recurring Service"
          code: "002"
          format: "XML"
          validation: "AFIP_compliant"

  # Tax Reporting
  tax_reporting:
    monthly_reports:
      generation: "automated"
      submission: "manual_review_then_automated"
      retention_period: "10 years"

      report_types:
        - name: "IVA Report"
          frequency: "monthly"
          due_date: "15th of following month"
          automation_level: "full"

        - name: "Income Report"
          frequency: "monthly"
          due_date: "20th of following month"
          automation_level: "semi-automated"

    annual_reports:
      generation: "semi-automated"
      review_required: "mandatory"
      retention_period: "10 years"

# Argentina Data Protection Law Compliance
data_protection_compliance:
  data_residency:
    primary_location: "Argentina (São Paulo region)"
    backup_location: "US East (DR only)"
    data_sovereignty: "compliant"

    # Data Classification
    data_classification:
      - type: "Personal Data"
        location: "sa-east-1"
        encryption: "AES-256"
        access_controls: "role-based"

      - type: "Financial Data"
        location: "sa-east-1"
        encryption: "AES-256"
        access_controls: "multi-factor"
