# Data Protection Configuration
data_protection:
  # Privacy Compliance Automation
  privacy_automation:
    # Data Subject Rights
    data_subject_rights:
      # Right to Access
      data_access:
        request_processing: "automated"
        response_time: "< 72 hours"
        data_format: "JSON/PDF"

      # Right to Rectification
      data_rectification:
        request_processing: "semi-automated"
        verification_required: "yes"
        response_time: "< 48 hours"

      # Right to Erasure
      data_erasure:
        request_processing: "automated"
        verification_required: "yes"
        response_time: "< 24 hours"

  # Data Breach Response
  breach_response:
    detection:
      automated_detection: "enabled"
      detection_time: "< 15 minutes"
      alert_channels: ["email", "slack", "sms"]

    response_procedures:
      - severity: "Critical"
        notification_time: "< 72 hours"
        authorities: ["AFIP", "Data Protection Authority"]
        affected_users: "immediate notification"

      - severity: "High"
        notification_time: "< 7 days"
        authorities: ["Data Protection Authority"]
        affected_users: "within 72 hours"

  # Encryption Standards
  encryption:
    at_rest:
      algorithm: "AES-256"
      key_management: "AWS KMS"
      key_rotation: "annual"

    in_transit:
      protocol: "TLS 1.3"
      certificate_authority: "Let's Encrypt"
      certificate_renewal: "automated"

    application_level:
      sensitive_fields: "encrypted"
      algorithm: "AES-256-GCM"
      key_derivation: "PBKDF2"
