# Disaster Recovery Testing Schedule
dr_testing_schedule:
  # Automated Tests
  automated_tests:
    - test_type: "Database Failover"
      frequency: "weekly"
      day: "Sunday"
      time: "02:00"
      duration: "30 minutes"
      success_criteria: "< 60 seconds failover time"

    - test_type: "Application Recovery"
      frequency: "bi-weekly"
      day: "Saturday"
      time: "01:00"
      duration: "45 minutes"
      success_criteria: "< 15 minutes recovery time"

  # Manual Tests
  manual_tests:
    - test_type: "Full DR Simulation"
      frequency: "quarterly"
      duration: "4 hours"
      participants: ["DevOps", "Engineering", "QA"]
      next_scheduled: "2024-12-15"

    - test_type: "Business Continuity Exercise"
      frequency: "semi-annually"
      duration: "8 hours"
      participants: ["All Teams", "Management"]
      next_scheduled: "2025-03-15"

# Recovery Validation Procedures
recovery_validation:
  data_integrity_checks:
    - "Database consistency verification"
    - "File system integrity check"
    - "Configuration validation"
    - "Application functionality test"

  performance_validation:
    - metric: "Response Time"
      threshold: "< 300ms"
      test_duration: "15 minutes"

    - metric: "Throughput"
      threshold: "> 80% of normal"
      test_duration: "30 minutes"
