# Enterprise Integration & Partnership Infrastructure
# BarberPro Day 10 - O10-001 Implementation
# Advanced API gateway and B2B integration platform

version: '3.8'

services:
  # Enterprise API Gateway
  enterprise-api-gateway:
    image: barberpro/enterprise-gateway:latest
    ports:
      - "443:443"
      - "80:80"
      - "8090:8090"  # Management API
    environment:
      - GATEWAY_MODE=enterprise
      - API_RATE_LIMITING=advanced
      - AUTHENTICATION_METHODS=jwt,oauth2,api_key,mutual_tls
      - PARTNER_RATE_LIMITS=10000/hour
      - WHITE_LABEL_ROUTING=enabled
      - API_VERSIONING=enabled
      - CORS_ENABLED=true
      - SECURITY_HEADERS=strict
    volumes:
      - ./gateway/enterprise-config.yaml:/etc/gateway/config.yaml
      - ./ssl/partners:/etc/ssl/partners
      - ./gateway/rate-limits:/etc/gateway/rate-limits
    networks:
      - integration-network
    depends_on:
      - partner-registry
      - integration-redis
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '3.0'
          memory: 6G

  # Partner Registry and Management
  partner-registry:
    image: barberpro/partner-registry:latest
    environment:
      - REGISTRY_DATABASE_URL=postgresql://integration_user:${INTEGRATION_DB_PASSWORD}@integration-database:5432/partner_registry
      - PARTNER_ONBOARDING=automated
      - API_KEY_GENERATION=enabled
      - PARTNER_ANALYTICS=enabled
      - SLA_MONITORING=enabled
      - PARTNER_PORTAL=enabled
    networks:
      - integration-network
    ports:
      - "8091:8080"
    depends_on:
      - integration-database
    deploy:
      replicas: 2

  # B2B Integration Hub
  b2b-integration-hub:
    image: barberpro/b2b-hub:latest
    environment:
      - INTEGRATION_PATTERNS=rest,graphql,webhook,soap,edi
      - MESSAGE_TRANSFORMATION=enabled
      - PROTOCOL_ADAPTATION=enabled
      - RELIABILITY_MONITORING=enabled
      - INTEGRATION_TESTING=enabled
      - PARTNER_CERTIFICATION=enabled
    volumes:
      - ./integrations/templates:/etc/integration-templates
      - ./integrations/mappings:/etc/data-mappings
    networks:
      - integration-network
    depends_on:
      - integration-message-broker
      - partner-registry
    deploy:
      replicas: 3

  # Webhook Infrastructure
  webhook-delivery-service:
    image: barberpro/webhook-service:latest
    environment:
      - DELIVERY_STRATEGY=at_least_once
      - RETRY_POLICY=exponential_backoff
      - MAX_RETRIES=5
      - INITIAL_DELAY=1000  # 1 second
      - MAX_DELAY=300000    # 5 minutes
      - WEBHOOK_VERIFICATION=hmac_sha256
      - DELIVERY_TRACKING=enabled
      - FAILURE_NOTIFICATIONS=enabled
    networks:
      - integration-network
    depends_on:
      - integration-redis
      - integration-message-broker
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '1.5'
          memory: 2G

  # White-label Deployment Automation
  white-label-deployer:
    image: barberpro/white-label-deployer:latest
    environment:
      - DEPLOYMENT_MODE=kubernetes
      - CUSTOMIZATION_ENGINE=enabled
      - AUTOMATED_TESTING=enabled
      - ROLLBACK_CAPABILITY=enabled
      - TENANT_ISOLATION=namespace
      - CUSTOM_DOMAINS=enabled
    volumes:
      - ./white-label/templates:/etc/templates
      - ./white-label/customizations:/etc/customizations
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - integration-network
    depends_on:
      - partner-registry
    deploy:
      placement:
        constraints:
          - node.role == manager

  # Enterprise Message Broker
  integration-message-broker:
    image: apache/kafka:3.5.1
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=integration-zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://integration-message-broker:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=2
      - KAFKA_NUM_PARTITIONS=12
    networks:
      - integration-network
    depends_on:
      - integration-zookeeper
    deploy:
      replicas: 3

  integration-zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2
    networks:
      - integration-network
    deploy:
      replicas: 3

  # Enterprise Redis Cluster for Caching
  integration-redis:
    image: redis:7-alpine
    command: >
      redis-server
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --maxmemory 4gb
      --maxmemory-policy allkeys-lru
    networks:
      - integration-network
    deploy:
      replicas: 6
      resources:
        limits:
          memory: 4G

  # Integration Database
  integration-database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=integration_platform
      - POSTGRES_USER=integration_user
      - POSTGRES_PASSWORD=${INTEGRATION_DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=partner_registry,webhook_logs,integration_logs,white_label_configs
      - MAX_CONNECTIONS=500
    volumes:
      - integration-db-data:/var/lib/postgresql/data
      - ./database/integration-init.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - integration-network

  # API Documentation Generator
  api-docs-generator:
    image: barberpro/api-docs:latest
    environment:
      - DOCS_FORMAT=openapi3,postman,insomnia
      - AUTO_GENERATION=enabled
      - INTERACTIVE_DOCS=enabled
      - CODE_SAMPLES=enabled
      - PARTNER_PORTAL_INTEGRATION=enabled
    volumes:
      - ./api-docs:/var/www/docs
    networks:
      - integration-network
    ports:
      - "8092:8080"
    depends_on:
      - enterprise-api-gateway

  # Integration Testing Service
  integration-testing:
    image: barberpro/integration-testing:latest
    environment:
      - TEST_AUTOMATION=enabled
      - PARTNER_SANDBOX=enabled
      - MOCK_SERVICES=enabled
      - LOAD_TESTING=enabled
      - CONTRACT_TESTING=enabled
    volumes:
      - ./testing/integration-tests:/tests
      - ./testing/mock-data:/mock-data
    networks:
      - integration-network
    depends_on:
      - b2b-integration-hub

  # Marketplace Integration Service
  marketplace-integration:
    image: barberpro/marketplace:latest
    environment:
      - SUPPORTED_MARKETPLACES=aws,azure,google_cloud,salesforce
      - AUTO_LISTING=enabled
      - PRICING_SYNCHRONIZATION=enabled
      - REVIEW_AGGREGATION=enabled
      - ANALYTICS_EXPORT=enabled
    networks:
      - integration-network
    depends_on:
      - partner-registry
      - integration-database

  # Third-party Service Integration
  third-party-integrations:
    image: barberpro/third-party-integrations:latest
    environment:
      - PAYMENT_GATEWAYS=mercadopago,stripe,paypal,square
      - CALENDAR_INTEGRATIONS=google,outlook,apple
      - COMMUNICATION=whatsapp,telegram,sms,email
      - ANALYTICS=google_analytics,mixpanel,amplitude
      - CRM_INTEGRATIONS=salesforce,hubspot,pipedrive
    volumes:
      - ./integrations/third-party-configs:/etc/configs
    networks:
      - integration-network
    depends_on:
      - b2b-integration-hub

  # Compliance and Audit Service
  compliance-audit:
    image: barberpro/compliance-audit:latest
    environment:
      - COMPLIANCE_FRAMEWORKS=gdpr,ccpa,sox,pci_dss,argentina_pdpa
      - AUDIT_LOGGING=comprehensive
      - DATA_LINEAGE_TRACKING=enabled
      - CONSENT_MANAGEMENT=enabled
      - DATA_RETENTION_POLICIES=automated
      - BREACH_DETECTION=enabled
    volumes:
      - compliance-audit-logs:/var/lib/audit-logs
    networks:
      - integration-network
    depends_on:
      - integration-database

  # Enterprise SSO Provider
  enterprise-sso:
    image: barberpro/enterprise-sso:latest
    environment:
      - SSO_PROTOCOLS=saml2,oidc,oauth2
      - IDENTITY_PROVIDERS=active_directory,azure_ad,okta,auth0
      - MFA_ENABLED=true
      - SESSION_MANAGEMENT=advanced
      - ATTRIBUTE_MAPPING=dynamic
    volumes:
      - ./sso/configurations:/etc/sso-configs
      - ./ssl/sso:/etc/ssl/sso
    networks:
      - integration-network
    ports:
      - "8443:8443"
    depends_on:
      - integration-database

  # Data Synchronization Service
  data-sync-service:
    image: barberpro/data-sync:latest
    environment:
      - SYNC_STRATEGIES=real_time,batch,event_driven
      - CONFLICT_RESOLUTION=last_writer_wins,merge,manual
      - DATA_TRANSFORMATION=enabled
      - SYNC_MONITORING=enabled
      - DELTA_SYNC=enabled
    networks:
      - integration-network
    depends_on:
      - integration-message-broker
      - integration-database

  # Partner Analytics Dashboard
  partner-analytics:
    image: barberpro/partner-analytics:latest
    environment:
      - ANALYTICS_ENGINE=clickhouse
      - REAL_TIME_METRICS=enabled
      - CUSTOM_DASHBOARDS=enabled
      - REPORT_GENERATION=automated
      - SLA_REPORTING=enabled
    networks:
      - integration-network
    ports:
      - "8093:8080"
    depends_on:
      - partner-registry
      - integration-database

  # Enterprise Notification Service
  enterprise-notifications:
    image: barberpro/enterprise-notifications:latest
    environment:
      - NOTIFICATION_CHANNELS=email,sms,push,webhook,slack
      - TEMPLATE_ENGINE=enabled
      - PERSONALIZATION=advanced
      - DELIVERY_TRACKING=enabled
      - A_B_TESTING=enabled
    networks:
      - integration-network
    depends_on:
      - integration-message-broker
      - integration-redis

  # Load Balancer for Enterprise Services
  enterprise-load-balancer:
    image: haproxy:2.8-alpine
    volumes:
      - ./load-balancer/enterprise-haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./ssl/load-balancer:/etc/ssl/private
    networks:
      - integration-network
    ports:
      - "8094:8080"  # Stats
    depends_on:
      - enterprise-api-gateway
    deploy:
      replicas: 2

networks:
  integration-network:
    driver: overlay
    encrypted: true
    attachable: false
    ipam:
      config:
        - subnet: 10.3.0.0/16

volumes:
  integration-db-data:
    driver: local
  compliance-audit-logs:
    driver: local

# Integration Templates
configs:
  rest-api-template:
    file: ./templates/rest-api-integration.yaml
  webhook-template:
    file: ./templates/webhook-integration.yaml
  oauth2-template:
    file: ./templates/oauth2-integration.yaml
  white-label-template:
    file: ./templates/white-label-config.yaml

# Partner Integration Presets
x-partner-integrations: &partner-integrations
  - name: payment_processor_integration
    type: payment_gateway
    authentication: api_key
    rate_limit: 1000/hour
    webhook_events: [payment_created, payment_completed, payment_failed]
    
  - name: calendar_integration
    type: calendar_service
    authentication: oauth2
    rate_limit: 5000/hour
    sync_frequency: real_time
    
  - name: crm_integration
    type: customer_relationship_management
    authentication: oauth2
    rate_limit: 2000/hour
    data_sync: bidirectional
    
  - name: analytics_integration
    type: analytics_service
    authentication: api_key
    rate_limit: unlimited
    data_export: batch_daily

# White-label Customization Options
x-white-label-options: &white-label-options
  - customization_level: basic
    features: [branding, colors, logo]
    deployment_time: 4h
    
  - customization_level: advanced
    features: [branding, custom_domains, feature_toggles, workflows]
    deployment_time: 24h
    
  - customization_level: enterprise
    features: [full_customization, custom_integrations, sla_guarantees]
    deployment_time: 7d