# BarberPro Infrastructure Scaling Configuration
# Day 7 Track A - Infrastructure Scaling & Performance Optimization
# Based on Day 6 success: 280 users, 35 providers, 4.7/5 rating

version: '1.0'
deployment_target: 'argentina-primary'
scaling_mode: 'auto-scaling'
target_environment: 'production'

# Auto-scaling Policies Based on Real Traffic Data
auto_scaling:
  web_servers:
    min_instances: 3
    max_instances: 15
    target_cpu_utilization: 70
    target_memory_utilization: 80
    scale_up_threshold: 85
    scale_down_threshold: 40
    scale_up_cooldown: 180  # 3 minutes
    scale_down_cooldown: 300  # 5 minutes
    
  backend_api:
    min_instances: 2 
    max_instances: 10
    target_cpu_utilization: 65
    target_memory_utilization: 75
    concurrent_users_threshold: 1400  # 5x current capacity
    requests_per_second_threshold: 100
    response_time_threshold: 200  # ms Argentina target
    
  booking_service:
    min_instances: 2
    max_instances: 8
    target_booking_queue_length: 50
    booking_processing_time_threshold: 3000  # ms
    peak_hour_scaling: true

# Load Balancer Optimization for Argentina Traffic
load_balancer:
  algorithm: 'weighted_round_robin'
  health_check:
    interval: 30
    timeout: 10
    healthy_threshold: 2
    unhealthy_threshold: 3
  
  argentina_optimization:
    primary_region: 'us-east-1'  # Closest to Argentina
    secondary_region: 'sa-east-1'  # São Paulo for South America
    latency_routing: true
    geo_proximity_bias: 'argentina'
    session_stickiness: true
    
  connection_settings:
    idle_timeout: 60
    connection_draining_timeout: 300
    enable_http2: true
    enable_compression: true

# Database Infrastructure Scaling (5x Traffic)
database:
  primary:
    instance_type: 'db.r6g.xlarge'  # Upgraded from large
    storage: '500GB'  # Increased from 100GB
    backup_retention: 7
    multi_az: true
    
  read_replicas:
    count: 3  # Increased from 1
    instance_type: 'db.r6g.large'
    regions: ['us-east-1a', 'us-east-1b', 'us-east-1c']
    
  connection_pooling:
    max_connections: 200  # Increased from 50
    connection_timeout: 30
    pool_size_per_service: 20
    
  performance_optimization:
    shared_preload_libraries: 'pg_stat_statements'
    effective_cache_size: '12GB'
    work_mem: '256MB'
    maintenance_work_mem: '2GB'
    checkpoint_completion_target: 0.9

# CDN Configuration for Argentina Geographic Distribution  
cdn:
  provider: 'cloudflare'
  argentina_optimization:
    edge_locations: ['buenos-aires', 'cordoba', 'rosario', 'mendoza']
    cache_policy: 'argentina-optimized'
    compression: 'brotli'
    
  caching_strategy:
    static_assets: '7d'
    api_responses: '5m'
    user_profiles: '1h'
    booking_data: '30s'
    payment_data: '0s'  # No caching
    
  performance_features:
    http3_enabled: true
    early_hints: true
    rocket_loader: true
    mirage: true
    polish: 'lossless'

# Advanced Caching Layers
caching:
  redis_cluster:
    nodes: 6  # Increased from 3
    node_type: 'cache.r6g.large'
    memory_per_node: '6.38GB'
    eviction_policy: 'allkeys-lru'
    
  application_cache:
    user_sessions: '24h'
    booking_availability: '5m'
    provider_profiles: '1h'
    service_catalog: '6h'
    payment_methods: '12h'
    
  database_query_cache:
    enabled: true
    size: '2GB'
    ttl: '1h'
    invalidation_strategy: 'tag-based'

# Resource Allocation Based on Usage Patterns
resource_allocation:
  peak_hours:
    argentina_timezone: 'America/Argentina/Buenos_Aires'
    morning_peak: '09:00-12:00'  # Barber appointments
    evening_peak: '17:00-20:00'  # After work bookings
    
  resource_scaling:
    morning_scale_factor: 1.5
    evening_scale_factor: 2.0
    weekend_scale_factor: 1.2
    
  cost_optimization:
    spot_instances: 40  # Percentage for non-critical workloads
    reserved_instances: 30  # Base capacity
    on_demand_instances: 30  # Peak scaling

# Monitoring and Alerting for Scaling Decisions
monitoring:
  infrastructure_metrics:
    - cpu_utilization
    - memory_utilization  
    - disk_io
    - network_throughput
    - connection_counts
    - response_times
    - error_rates
    
  business_metrics:
    - concurrent_users
    - booking_conversion_rate
    - payment_success_rate
    - user_satisfaction_score
    - argentina_market_penetration
    
  alerting_thresholds:
    critical:
      response_time: 500  # ms
      error_rate: 5  # percentage
      cpu_utilization: 90
      memory_utilization: 95
      
    warning:
      response_time: 300  # ms
      error_rate: 2  # percentage
      cpu_utilization: 80
      memory_utilization: 85

# Security Scaling for Increased Attack Surface
security:
  waf_rules:
    rate_limiting: 
      requests_per_minute: 120  # Increased from 60
      burst_capacity: 200
    
    argentina_geo_blocking: false  # Allow Argentina traffic
    suspicious_activity_threshold: 'medium'
    
  ddos_protection:
    enabled: true
    sensitivity: 'medium'
    automatic_mitigation: true
    
  ssl_termination:
    protocol: 'TLSv1.3'
    cipher_suites: 'modern'
    hsts_enabled: true
    
# Backup and Disaster Recovery for Scaled Infrastructure
backup_strategy:
  database:
    point_in_time_recovery: true
    automated_backups: true
    backup_window: '03:00-04:00'  # Argentina night hours
    cross_region_backup: true
    
  application_data:
    user_uploads: 'daily'
    configuration: 'real-time'
    logs: '7d_retention'
    
  disaster_recovery:
    rto: 15  # Recovery Time Objective (minutes)
    rpo: 5   # Recovery Point Objective (minutes)
    failover_region: 'sa-east-1'
    
# Cost Optimization for Scaling Efficiency
cost_optimization:
  reserved_capacity:
    commitment: '1_year'
    payment_option: 'partial_upfront'
    coverage: 60  # percentage of baseline capacity
    
  scheduled_scaling:
    scale_down_hours: '02:00-06:00'  # Argentina night
    weekend_optimization: true
    holiday_calendar: 'argentina'
    
  resource_tagging:
    cost_center: 'barberpro-infrastructure'
    environment: 'production'
    scaling_group: 'auto-scaling'
    region: 'argentina-optimized'